---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitops-primer

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitops-primer
rules:
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - anyuid
    resources:
      - securitycontextconstraints
    verbs:
      - use
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["list", "get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitops-primer
  namespace: developer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitops-primer
subjects:
  - kind: ServiceAccount
    name: gitops-primer
