name: Validate Primer

on: pull_request

jobs:
  create-cluster:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        KUBERNETES_VERSIONS: ["1.20.2"]
    env:
      KUBECONFIG: /tmp/kubeconfig
      KUBERNETES_VERSION: ${{ matrix.KUBERNETES_VERSIONS }}
    steps:
      - name: Create k8s Kind Cluster
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v${KUBERNETES_VERSION}"

      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/v${KUBERNETES_VERSION}/bin/linux/amd64/kubectl"
          sudo install ./kubectl /usr/local/bin/
          kubectl version --short --client
          kubectl version --short --client | grep -q ${KUBERNETES_VERSION}

          
