name: Validate Primer

on: pull_request

jobs:
  create-cluster:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        KUBERNETES_VERSIONS: ["1.20.2"]
    env:
      KUBECONFIG: /tmp/kubeconfig
      KUBERNETES_VERSION: ${{ matrix.KUBERNETES_VERSIONS }}
    steps:
      - name: Create k8s Kind Cluster
        uses: engineerd/setup-kind@v0.5.0

      - name: Checkout source
        uses: actions/checkout@v2

      - name: create the job
        run: |
          kubectl create -f job.yaml
